server:
  port: 8080


customerClient:
  url: 'localhost:8082'

pointsCalculatorClient:
  url: 'localhost:8081'

feign:
  client:
    config:
      customerClient:
        connectTimeout: 5000
        readTimeout: 5000