server:
  port: 8080

spring:
  application:
    name: api-gateway-service
#  sleuth:
#    otel:
#      exporter:
#        otlp:
#          endpoint: http://localhost:4317
  sleuth:
    propagation:
      type: B3,W3C
    opentracing:
      enabled: true
    base-url:
      http://localhost:9411

customerClient:
  url: localhost:8082

pointsCalculatorClient:
  url: localhost:8081

feign:
  client:
    config:
      customerClient:
        connectTimeout: 5000
        readTimeout: 5000