server:
  port: 8081

spring:
  application:
    name: points-service
  sleuth:
    propagation:
      type: B3,W3C
    opentracing:
      enabled: true
    base-url:
      http://localhost:9411

points:
  cpp: 4